### ISSUE TITLE
Unable to start rails server: Ubuntu 18.04 (AWS EC2 instance)

### ISSUE THREAD

**Issue by dusadvarshit** [flatplanet/railsfriends#1]
System use: ubuntu 18.04 (AWS EC2)

I installed ruby & rails using the tutorial presented here: https://gorails.com/setup/ubuntu/20.10

I was able to run the tutorial example presented in the above link and get the rails server running. 

However, today I came across the railsfriends tutorial on Youtube and attempted to follow the project. Unfortunately after forking the directory and trying to start the rails server, I keep getting the following error.

Ignoring executable-hooks-1.6.0 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.0
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
Traceback (most recent call last):
        4: from bin/rails:3:in `<main>'
        3: from bin/rails:3:in `require_relative'
        2: from /home/ubuntu/varshit/rails/railsfriends/config/boot.rb:3:in `<top (required)>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)

I am quite confused about the above. 
My rvm list gives me the following:

=> ruby-2.6.6 [ x86_64 ]
 * ruby-2.7.2 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

However, the system had ruby (I think by default to 2.5.0).  

I am completely unsure why this is happening and why I can run right rails from one project and not from another.

**Comment by earningideasgroup** [comment]
Repeat this process again!

**Comment by oc-2** [comment]
Probably because the project was created with Windows.
